[tool.poetry]
name = "vesting-example-helios"
version = "0.1.0"
description = ""
authors = ["et <et>"]

[tool.poetry.dependencies]
python = "^3.10"
pycardano = "^0.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
